<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250606041857 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE greeting_id_seq CASCADE');
        $this->addSql('CREATE TABLE bean_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE coffee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, roaster_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_538529B3CA7ADAEA ON coffee (roaster_id)');
        $this->addSql('CREATE TABLE coffee_bean (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, percent INT NOT NULL, coffee_id INT NOT NULL, type_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_898BCA7178CD6D6E ON coffee_bean (coffee_id)');
        $this->addSql('CREATE INDEX IDX_898BCA71C54C8C93 ON coffee_bean (type_id)');
        $this->addSql('CREATE TABLE roaster (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, rating INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE coffee ADD CONSTRAINT FK_538529B3CA7ADAEA FOREIGN KEY (roaster_id) REFERENCES roaster (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE coffee_bean ADD CONSTRAINT FK_898BCA7178CD6D6E FOREIGN KEY (coffee_id) REFERENCES coffee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE coffee_bean ADD CONSTRAINT FK_898BCA71C54C8C93 FOREIGN KEY (type_id) REFERENCES bean_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE greeting');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE greeting_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE greeting (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE coffee DROP CONSTRAINT FK_538529B3CA7ADAEA');
        $this->addSql('ALTER TABLE coffee_bean DROP CONSTRAINT FK_898BCA7178CD6D6E');
        $this->addSql('ALTER TABLE coffee_bean DROP CONSTRAINT FK_898BCA71C54C8C93');
        $this->addSql('DROP TABLE bean_type');
        $this->addSql('DROP TABLE coffee');
        $this->addSql('DROP TABLE coffee_bean');
        $this->addSql('DROP TABLE roaster');
    }
}
