<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250606070353 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE coffee_origin (coffee_id INT NOT NULL, origin_id INT NOT NULL, PRIMARY KEY(coffee_id, origin_id))');
        $this->addSql('CREATE INDEX IDX_B6422FF078CD6D6E ON coffee_origin (coffee_id)');
        $this->addSql('CREATE INDEX IDX_B6422FF056A273CC ON coffee_origin (origin_id)');
        $this->addSql('CREATE TABLE origin (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, country VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE coffee_origin ADD CONSTRAINT FK_B6422FF078CD6D6E FOREIGN KEY (coffee_id) REFERENCES coffee (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE coffee_origin ADD CONSTRAINT FK_B6422FF056A273CC FOREIGN KEY (origin_id) REFERENCES origin (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE coffee_origin DROP CONSTRAINT FK_B6422FF078CD6D6E');
        $this->addSql('ALTER TABLE coffee_origin DROP CONSTRAINT FK_B6422FF056A273CC');
        $this->addSql('DROP TABLE coffee_origin');
        $this->addSql('DROP TABLE origin');
    }
}
