<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250606072047 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE roast_level (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level VARCHAR(255) DEFAULT \'medium\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE coffee ADD roast_level_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE coffee DROP roast_level');
        $this->addSql('ALTER TABLE coffee ADD CONSTRAINT FK_538529B34FD42A5A FOREIGN KEY (roast_level_id) REFERENCES roast_level (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_538529B34FD42A5A ON coffee (roast_level_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE roast_level');
        $this->addSql('ALTER TABLE coffee DROP CONSTRAINT FK_538529B34FD42A5A');
        $this->addSql('DROP INDEX IDX_538529B34FD42A5A');
        $this->addSql('ALTER TABLE coffee ADD roast_level VARCHAR(255) DEFAULT \'medium\' NOT NULL');
        $this->addSql('ALTER TABLE coffee DROP roast_level_id');
    }
}
